### PR TITLE
Move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by olexandr-konovalov**

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@beick I am trying to set up automated tests to have them ready for your incoming changes. 

This currently fails, by different reasons. First, we need to install singular as an apt package. Second, the template from the example packages relies on GAPDoc manuals - either need to drop that test, or adapt it to gapmacro-based documentation. @fingolfin @ssiccha any packages I can use as a model?

**Comment by olexandr-konovalov** [comment]
Singular now installed. Looking at making manuals.

**Comment by olexandr-konovalov** [comment]
I will merge this for now, it works for package tests, we can add building the manual later.

**Comment by ssiccha** [comment]
I have never used gapmacro based documentation I think.

**Pull request merged**
